<h1>Welcome</h1>

<form action="/contact-list/add" method="post">
First Name <input type="text" name="first-name"/><br/>
Last Name <input type="text" name="last-name"/><br/>
Email <input type="text" name="email"/><br/>
<button type="submit" name="add" value="Add">Add</button>
</form>


<h1>
    Contacts
</h1>

<?php 
	foreach ($contacts as $contact) {
		echo $contact->first_name . "<br/>";
		echo $contact->last_name . "<br/>";
		echo $contact->email . "<br/>";
		echo "<br/><br/>";
	}
?>